server.port=8080
spring.application.name=brosport

spring.datasource.url=jdbc:mysql://localhost:3306/brosport_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=447724
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

cloudinary.cloud_name=ddmjwvlhk
cloudinary.api_key=567562822235166
cloudinary.api_secret=MtduOYwGGBZGlNpdra1z8bmNWfI

spring.elasticsearch.uris=http://localhost:9200

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vmvhlls123@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true